#!/usr/bin/env python3
import os
import datetime
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PAPERS_DIR = os.path.join(BASE_DIR, "infinity_papers")
COUNTER_FILE = os.path.join(PAPERS_DIR, "blue_token_counter.json")
BODY_FILE = os.path.join(BASE_DIR, "draft_body_ionization.txt")

os.makedirs(PAPERS_DIR, exist_ok=True)

# ---- CONFIG BLOCK (edit these when you want a different paper) ----
CART_ID      = "CART101"
CATEGORY     = "physics_quantum"
SEARCH_TERM  = "ionization"
TOKEN_COLOR  = "BLUE"

# This matches your PAPER 09 • BLUE example
SOURCE_TAG   = "PAPER 09 • BLUE"
SOURCE_LINK  = "/38671158/"

TITLE        = "Pharmacokinetic Models for Inhaled Fluticasone Propionate and Salmeterol Xinafoate to Quantify Batch-to-Batch Variability."
# -------------------------------------------------------------------

def load_body():
    if os.path.exists(BODY_FILE):
        with open(BODY_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return (
        "## Infinity Token Narrative\n"
        "This token encodes research generated by the Infinity operating system "
        "using external physics/quantum data streams (NASA, CERN, DOE, arXiv, APS, etc.).\n\n"
        "Body text placeholder – edit draft_body_ionization.txt with your full narrative."
    )

def load_counter():
    if not os.path.exists(COUNTER_FILE):
        return {"next_token": 287711}  # start where your example left off
    with open(COUNTER_FILE, "r") as f:
        return json.load(f)

def save_counter(counter):
    with open(COUNTER_FILE, "w") as f:
        json.dump(counter, f)

def compute_value(body_text, links_count):
    # simple version of your “bytes + http link count” logic
    byte_len = len(body_text.encode("utf-8"))
    return byte_len + links_count * 1000

def main():
    counter = load_counter()
    token_number = counter["next_token"]

    body = load_body()
    links_count = 1  # we have one explicit blue link in this config
    token_value = compute_value(body, links_count)

    now = datetime.datetime.now().isoformat()
    filename = f"PAPER_{token_number}_{TOKEN_COLOR}_{SEARCH_TERM}.md"
    out_path = os.path.join(PAPERS_DIR, filename)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# ∞ Infinity Research Paper\n")
        f.write(f"## Cart: {CART_ID} / Category: {CATEGORY}\n")
        f.write(f"## Token #: {token_number}\n")
        f.write(f"## Token Value: {token_value}\n")
        f.write(f"## Token Color: {TOKEN_COLOR}\n")
        f.write(f"## Generated: {now}\n\n")

        f.write(f"## Search Term\n{SEARCH_TERM}\n\n")
        f.write("---\n\n")

        f.write("## Source Link (Blue = you get paid to finish this)\n")
        f.write(f"[{SOURCE_TAG}]({SOURCE_LINK})\n\n")

        f.write(body)
        f.write("\n")

    counter["next_token"] = token_number + 1
    save_counter(counter)

    print("[∞] Infinity Research Paper minted")
    print(f"[∞] Token #:     {token_number}")
    print(f"[∞] Token Value: {token_value}")
    print(f"[∞] Color:       {TOKEN_COLOR}")
    print(f"[∞] File:        {out_path}")

if __name__ == "__main__":
    main()
