#!/usr/bin/env python3
"""
cart016_metadata_writer
Generates metadata.json for SEO & social sharing.
"""

import json

def main():
    with open("project.json") as f:
        project = json.load(f)

    metadata = {
        "title": project["intent"],
        "description": f"A {project['site_type']} website generated from intent.",
        "og:type": "website",
        "og:title": project["intent"],
        "og:description": "Generated by co-star_coder",
        "twitter:card": "summary_large_image"
    }

    with open("metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    print("[✓] metadata.json created")

if __name__ == "__main__":
    main()
